# image:
#     file: .gitpod.Dockerfile
  
#   tasks:
#     - init: yarn install && bundle install

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: rvm install 2.7 && bundle install && yarn install --check-files
    command: rails server