# image:
#     file: .gitpod.Dockerfile
  
#   tasks:
#     - init: yarn install && bundle install

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server