# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the containers
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Yarn Check
      run: docker ecec project-matching_rails_1 yarn install --check-files
    - name: Create database
      run: docker exec project-matching_rails_1 bundle exec rake db:create
    - name: Migrate Database
      run: docker exec project-matching_rails_1 bundle exec rake db:migrate
    - name: Run tests
      run: docker exec project-matching_rails_1 bundle exec rake test -d 
  
